Error in line 20:with open('myfile.txt','r') as f:
Solution:Mention the proper filename. 